apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sendgrid-stats-exporter.secretName" . }}
  labels:
  {{- include "sendgrid-stats-exporter.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.secret.username | b64enc | quote }}
  apiKey: {{ .Values.secret.apiKey | b64enc | quote }}