---
version: 2.1

orbs:
  # https://circleci.com/developer/orbs/orb/circleci/go
  go: circleci/go@1.5.0

workflows:
  version: 2
  main:
    jobs:
      - go_build:
          filters:
            tags:
              only: /.*/
      - docker_build:
          context: "DockerHub"
          filters:
            tags:
              only: /.*/

jobs:
  go_build:
    executor:
      name: go/default
      tag: '1.15'
    steps:
      - checkout
      - go/mod-download-cached
      - run: make
  docker-build:
    docker:
      - image: chatwork/circleci-docker:18.09.3
    environment:
      - CIRCLECI_WORKSPACE: /root/project
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 18.09.3
      - run: docker login -u="${DOCKER_REGISTRY_USERNAME}" -p="${DOCKER_REGISTRY_PASSWORD}"
      - run: make build-image